# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

workspace 'QuickTraceiOSLoggerDemo.xcworkspace'
project 'QuickTraceiOSLoggerDemo.xcodeproj'

target 'QuickTraceiOSLoggerDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for QuickTraceiOSLoggerDemo
  pod 'QuickTraceiOSLogger', :path => '../'
end
